# Tarea día 8
**Programación I**

**Marybeth Rodríguez**

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [11]:
import numpy as np
import random

filas=10 #Ingresa el numero de filas de la matriz
columnas=10 #Ingresa el numero de columnas de la matriz
X=np.zeros(filas*columnas) #Genera una matriz de ceros
y= int(filas*columnas/2) #Devuelve la mitad de los valores de los datos ingresados
print(y)
X[:y]=1 #Asigna valor de 1 a la mitad de los datos
np.random.shuffle(X)#acomoda de forma aleaatoria los valores de la matriz
X.reshape(filas,columnas)#arregla los datos en forma de matriz, de acuerdo a las dimensiones de filas y columnas ingresadas

50


array([[1., 1., 1., 0., 0., 1., 1., 1., 0., 0.],
       [0., 1., 1., 0., 1., 1., 0., 0., 1., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
       [1., 0., 0., 1., 0., 1., 0., 0., 0., 1.],
       [1., 1., 0., 0., 1., 1., 1., 0., 0., 1.],
       [1., 1., 0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 1., 1., 1., 1., 1., 0., 0., 1., 0.],
       [1., 1., 1., 1., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0., 1.]])

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 
2.	Apile ambos vectores a lo largo de una tercera dimensión. 
3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 


In [12]:
#Inciso 1
a= np.zeros([5,2],dtype=int)# se genera una matriz de ceros con dimensión (5,2)
print(a)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [13]:
b=np.ones([5,2], dtype=int)# se genera una matriz de unos con dimensión (5,2)
print(b)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [14]:
x= a.flatten() #La matriz de (5,2) se transforma en una única lista

print(x[:,None])# de esta manera se imprime cada valor de la lista como valores individuales (columnas)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [15]:
y= b.flatten() #La matriz de (5,2) se transforma en una única lista
print(y[:,None]) # de esta manera se imprime cada valor de la lista como valores individuales (columnas)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [16]:
#Inciso 2
np.dstack((x,y))#apila los vectores generados anteriormente en otra dimensión

array([[[0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1]]])

In [17]:
#Inciso 3
j= np.concatenate((x[:,None],y[:,None]), axis=0)
''' se convierten los vectores originales en vectores filas y luego los 
concatena'''
j

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios, donde cada columna sea una variable. 
2.	Evalúe la matriz anterior en la función. El resultado debe ser una vector columna. 

In [18]:
def f(matriz): #se define la función respecto a la matriz construida aleatoriamente
    return 2*matriz[:,0] + 3*matriz[:,1]+matriz[:,2]**2

In [113]:
filas = int(input("Ingrese el número de filas"))
M= np.floor(10*np.random.random((filas, 3)))
print(f(M)[:,None])


Ingrese el número de filas4
[[38.]
 [42.]
 [31.]
 [64.]]


## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

In [125]:
Square50 = np.random.randint(2, size=(50,50))#definimos aleatoriamente las posiciones en donde se caeran los tiros(1)
x= Square50.sum() #se suma la cantidad de tiros registrados dentro del cuadrado grande
x

1233

In [126]:
Square20=Square50[14:34, 14:34] # se delimita el espacio correspondiente al cuadrado pequeño
y=Square20.sum()
y

202

In [127]:
AG=(50*50)# se calcula el área del cuadrado grande
AG

2500

In [128]:
AP=(AG*y)/x # se calcula el area pequeña 
AP

409.5701540957015

## Ejercicio 5

### *Tarea*

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    



**1.Eye** 

Devuelve una matriz 2D con "1" en diagonal y "0" en otro lugar.


In [89]:
np.eye(4, k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**2.Full** 



Devuelve una nueva matriz de forma y tipo dados, rellena sin fill_value.


In [93]:
np.full((3, 2), "hola")

array([['hola', 'hola'],
       ['hola', 'hola'],
       ['hola', 'hola']], dtype='<U4')

**3.Asarray**

Convierte la entrada en una matriz

In [98]:
a = [2, 2],3,5
np.asarray(a)

array([list([2, 2]), 3, 5], dtype=object)

**4.Logspace** 

Números de retorno espaciados uniformemente en escala logarítmica de registro

In [100]:
np.logspace(3.0, 5.0, num=4)

array([  1000.        ,   4641.58883361,  21544.34690032, 100000.        ])

**5.Diag** 

Extraer una diagonal o construir una matriz diagonal

In [107]:
x=np.arange(4).reshape(2,2)
print (x)
np.diag(x)

[[0 1]
 [2 3]]


array([0, 3])

**6.Tri** 

Una matriz con "1" en y por debajo de la diagonal dada y "0" en otro lugar.

In [111]:
x= np.tri(4, 4, 0, dtype=int)
x

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 1, 1, 1]])

**7.Tril** 

Triángulo inferior de una matriz.
Devuelve una copia de una matriz con elementos por encima de la diagonal k con valores iguales a cero

In [132]:
np.tril([[2,2,8],[3,5,6],[4,4,1]], 0)

array([[2, 0, 0],
       [3, 5, 0],
       [4, 4, 1]])

**8.Split** 

Divida una matriz en varias submatrices 

In [139]:
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

**9.Vsplit**

Dividir una matriz en varias submatrices verticalmente (en cuanto a fila)


In [141]:
x = np.arange(16.0).reshape(4, 4)
print(x)
np.vsplit(x, 2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

**10.Insert**

Inserte valores a lo largo del eje dado antes de los índices dados

In [148]:
a = np.array([[2, 7], [3, 2], [9, 5]])
print(a)
np.insert(a, 4, 6)

[[2 7]
 [3 2]
 [9 5]]


array([2, 7, 3, 2, 6, 9, 5])

**11.Append**

Anexar valores al final de una matriz

In [149]:
np.append([2, 8], [[4, 5, 6], [7, 8, 9]])

array([2, 8, 4, 5, 6, 7, 8, 9])

**12.Unique**

Encuentra los elementos únicos de una matriz

In [150]:
np.unique([4, 4, 2, 1, 3, 3])

array([1, 2, 3, 4])

**13.Roll**

Rodar elementos de matriz a lo largo de un eje determinado

In [152]:
x = np.arange(10)
np.roll(x, 2)

array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

**14.Rot90**

Gire una matriz 90 grados en el plano especificado por los ejes.

In [153]:
m = np.array([[2,8],[4,9]], int)
print(m)
np.rot90(m)

[[2 8]
 [4 9]]


array([[8, 9],
       [2, 4]])

**15.Rot90**

Gire una matriz 90 grados en el plano especificado por los ejes.

In [156]:
x = np.array([2, 4])
print(x.shape)
y = np.expand_dims(x, axis=0)
print(y)
print(y.shape)

(2,)
[[2 4]]
(1, 2)


**16.Tile**

Construya una matriz repitiendo A el número de veces que indican los representantes.

In [159]:
a = np.array([2, 5, 3])
np.tile(a, 3)

array([2, 5, 3, 2, 5, 3, 2, 5, 3])

**17.DSplit**

Dividir matriz en varias submatrices a lo largo del 3er eje

In [162]:
x = np.arange(16.0).reshape(2, 2, 4)
x
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]), array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

**18.HSplit**

Dividir una matriz en varias submatrices horizontalmente (en cuanto a columnas)

In [163]:
x = np.arange(16.0).reshape(4, 4)
print(x)

np.hsplit(x, 2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

**19.Repeat**

Repetir elementos de una matriz

In [164]:
np.repeat(3, 4)


array([3, 3, 3, 3])

**20.Swapaxes**

Intercambia dos ejes de una matriz

In [166]:
x = np.array([[1,2,3]])
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])

**21.Capitalize**


In [168]:
c = np.array(['a1b2','1b2a','b2a1','2a1b'],'S4'); c
np.char.capitalize(c)

array([b'A1b2', b'1b2a', b'B2a1', b'2a1b'], dtype='|S4')

**22. Lower**

In [169]:
c = np.array(['A1B C', '1BCA', 'BCA1']); c
np.char.lower(c)

array(['a1b c', '1bca', 'bca1'], dtype='<U5')

**23. Lstrip**

In [172]:
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
print(c)
np.char.lstrip(c, 'a')

['aAaAaA' '  aA  ' 'abBABba']


array(['AaAaA', '  aA  ', 'bBABba'], dtype='<U7')

**24. Rstrip**

In [173]:
c = np.array(['aAaAaA', 'abBABba'], dtype='S7'); c
print(c)
np.char.rstrip(c, b'a')

[b'aAaAaA' b'abBABba']


array([b'aAaAaA', b'abBABb'], dtype='|S7')

**25.Strip**

In [176]:
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
print(c)
np.char.strip(c)

['aAaAaA' '  aA  ' 'abBABba']


array(['aAaAaA', 'aA', 'abBABba'], dtype='<U7')

**26.Title**

In [177]:
c=np.array(['a1b c','1b ca','b ca1','ca1b'],'S5'); c
np.char.title(c)

array([b'A1B C', b'1B Ca', b'B Ca1', b'Ca1B'], dtype='|S5')

**27.Upper**

In [178]:
c = np.array(['a1b c', '1bca', 'bca1']); c
np.char.upper(c)

array(['A1B C', '1BCA', 'BCA1'], dtype='<U5')

**28.Count**

In [179]:
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
c
np.char.count(c, 'A')

array([3, 1, 1])

**29.Endswith**

In [183]:
s = np.array(['foo', 'bar'])
print(s[0]) 
print(s[1])
print (s)

np.char.endswith(s, 'ar')

foo
bar
['foo' 'bar']


array([False,  True])


**30.Fliplr**

In [184]:
A = np.diag([1.,2.,3.])
A
np.fliplr(A)

array([[0., 0., 1.],
       [0., 2., 0.],
       [3., 0., 0.]])

**31.Empty_like**

In [185]:
a = ([1,2,3], [4,5,6])                       
np.empty_like(a)

array([[         0, 1072693248,          0],
       [1073741824,          0, 1074266112]])

**32.Zeros_like**

In [186]:
x = np.arange(6)
x = x.reshape((2, 3))
print(x)
np.zeros_like(x)

[[0 1 2]
 [3 4 5]]


array([[0, 0, 0],
       [0, 0, 0]])

**33.Ascontiguousarray**

In [187]:
x = np.arange(6).reshape(2,3)
np.ascontiguousarray(x, dtype=np.float32)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

**34.Asmatrix**

In [192]:
 x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
x=[0,0] 
m


matrix([[1, 2],
        [3, 4]])

**35.Fromiter**

In [195]:
iterable = (x*x for x in range(5))
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

**36.Fromstring**

In [196]:
np.fromstring('1 2', dtype=int, sep=' ')

array([1, 2])

**37.Bitwise_and**

In [197]:
np.bitwise_and(13, 17)

1

**38.Bitwise_or**

In [198]:
np.bitwise_or(13, 16)

29

**39.Bitwise_xor**

In [199]:
np.bitwise_xor(13, 17)

28

**40.Invert**

In [201]:
x = np.invert(np.array(13, dtype=np.uint8))
x

242

**41.Left_shift**

In [202]:
np.left_shift(5, 2)

20

**42.Right_shift**

In [203]:
np.right_shift(10, 1)

5

**43.Packbits**


In [204]:
a = np.array([[[1,0,1],
...                [0,1,0]],
...               [[1,1,0],
...                [0,0,1]]])
b = np.packbits(a, axis=-1)
b

array([[[160],
        [ 64]],

       [[192],
        [ 32]]], dtype=uint8)


**44.Unpackbits**

In [205]:
a = np.array([[2], [7], [23]], dtype=np.uint8)
print (a)

b = np.unpackbits(a, axis=1)
print(b)

[[ 2]
 [ 7]
 [23]]
[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 1 0 1 1 1]]


**45.Binary_repre**

In [207]:
np.binary_repr(5)

'101'

**44.Binary_repre**

In [208]:
np.binary_repr(3)

'11'

**45.Swapcase**

In [209]:
c=np.array(['a1B c','1b Ca','b Ca1','cA1b'],'S5'); 
np.char.swapcase(c)

array([b'A1b C', b'1B cA', b'B cA1', b'Ca1B'], dtype='|S5')

**46.Compare_chararrays**

In [210]:
a = np.array(["a", "b", "cde"])
b = np.array(["a", "a", "dec"])
np.compare_chararrays(a, b, ">", True)

array([False,  True, False])

**47.Chararray**

In [214]:
charar = np.chararray((3, 3))
charar[:]='a'
charar

chararray([[b'a', b'a', b'a'],
           [b'a', b'a', b'a'],
           [b'a', b'a', b'a']], dtype='|S1')

**47.Delete**

In [215]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
np.delete(arr, 1, 0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

**48.Resize**

In [216]:
a=np.array([[0,1],[2,3]])
print(np.resize(a,(2,3)))

np.resize(a,(1,4))

[[0 1 2]
 [3 0 1]]


array([[0, 1, 2, 3]])

**49.Trip_zeros**

In [217]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trim_zeros(a)

array([1, 2, 3, 0, 2, 1])

**50.Identity**

In [219]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

**51.Ones**

In [220]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

**52.Ones_like**

In [221]:
x = np.arange(6)
x = x.reshape((2, 3))
print(x)

np.ones_like(x)

[[0 1 2]
 [3 4 5]]


array([[1, 1, 1],
       [1, 1, 1]])

**53.Asarray**

In [222]:
a = [1, 2]
np.asarray(a)

array([1, 2])

**54.Asanayarray**

In [223]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

**55.Ascontiguosarray**

In [224]:
x = np.arange(6).reshape(2,3)
np.ascontiguousarray(x, dtype=np.float32)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

**56.Frombuffer**

In [225]:
s = b'hello world'
np.frombuffer(s, dtype='S1', count=5, offset=6)

array([b'w', b'o', b'r', b'l', b'd'], dtype='|S1')

**57.Fromfunction**

In [226]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

**58.Core.records.fromarrays**

In [227]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
print(r[1])

(2, 'dd', 2.)


**59.Core.records.fromrecords**

In [228]:
r=np.core.records.fromrecords([(456,'dbe',1.2),(2,'de',1.3)],
... names='col1,col2,col3')
print(r[0])

(456, 'dbe', 1.2)


**60.Core.records.fromrecords**

In [229]:
np.arange(3)

array([0, 1, 2])

**61.Linspace**

In [230]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

**62.Geomspace**

In [231]:
np.geomspace(1, 1000, num=4)

array([   1.,   10.,  100., 1000.])


**63.Meshgrid**

In [232]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
xv

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

**64.Meshgrid**

In [233]:
np.mgrid[0:5,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

**65.Meshgrid**

In [234]:
from numpy import ogrid
ogrid[-1:1:5j]

array([-1. , -0.5,  0. ,  0.5,  1. ])

**66.Diagflat**

In [235]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

**67.Vander**

In [236]:
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

**68.Bmat**

In [237]:
A = np.mat('1 1; 1 1')
B = np.mat('2 2; 2 2')
C = np.mat('3 4; 5 6')
D = np.mat('7 8; 9 0')
np.bmat([[A, B], [C, D]])

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

**69.Zeros**


In [238]:
 np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

**70.Loadtext**

In [239]:
from io import StringIO   
c = StringIO(u"0 1\n2 3")
np.loadtxt(c)

array([[0., 1.],
       [2., 3.]])

**71.Ndarray.flat**

In [240]:
x = np.arange(1, 7).reshape(2, 3)
x

x.flat[3]

4

**72.Ndarray.flatten**

In [242]:
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

**73.Movexaxis**

In [243]:
x = np.zeros((3, 4, 5))
np.moveaxis(x, 0, -1).shape

(4, 5, 3)

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    


In [252]:
import numpy as np
x = np.random.random((3,3))
y = np.arange(1,9,3)

np.savez('cambios.bin', objX = x, objY = y)

In [253]:
j=np.load('cambios.bin.npz')

In [254]:
j['objX']

array([[0.07013927, 0.0218612 , 0.2589961 ],
       [0.46860343, 0.86117183, 0.64989684],
       [0.74052787, 0.64532974, 0.17995273]])

In [255]:
j['objY']

array([1, 4, 7])

3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    


In [256]:
x = np.arange(1,9,3)
y = np.random.random((3,3))
np.savetxt('Savetxt', y, delimiter=',')   

In [257]:
np.loadtxt('Savetxt', delimiter=',')

array([[0.14512194, 0.43034042, 0.77679439],
       [0.0140322 , 0.12555408, 0.02588749],
       [0.64039904, 0.84163753, 0.13119798]])

4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

In [292]:
def EstimacionMCO():
    Archivo= str(input("Ingrese el nombre de archivo csv."))+".csv"
    info = np.genfromtxt(Archivo,delimiter=',')
    X=info[:,0:6]
    Y=info[:,6:7]
    A=(X.T)@X
    B=(X.T)@Y
    Beta=((np.linalg.inv(A))@B)
    return Beta
    

In [293]:
EstimacionMCO()

Ingrese el nombre de archivo csv.Tarea8


array([[ 0.41570162],
       [ 0.36205366],
       [-0.04193507],
       [ 0.07624416],
       [ 0.0565028 ],
       [ 0.09779215]])